services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
      - backend_db:/app/database
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/todo-magusai:/app/todo-magusai
      - frontend_node_modules:/app/node_modules
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"   # SMTP (küldéshez)
      - "8025:8025"   # Web UI
    restart: always

volumes:
  backend_node_modules:
  frontend_node_modules:
  backend_db: